resources:
- repo: self

queue:
  name: Hosted VS2017
  demands: azureps

trigger:
- master

variables:
  StorageAccount: 'dddbnetest'
  StorageContainer: 'ddd-functions'
  Parameters.RestoreBuildProjects: ''
  Parameters.TestProjects: ''
  BuildConfiguration: 'Release'
  
steps:
- task: Npm@1
  inputs:
    workingDir: DDD.Functions
    verbose: false

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'DDD.Functions\DDD.Functions.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)'
    modifyOutputPath: false

- task: AzureFileCopy@1
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)\$(Build.BuildNumber).zip'
    azureSubscription: 'Pay-As-You-Go(a69a9494-70b6-40e9-866a-0fd2d8382691)'
    Destination: AzureBlob
    storage: '$(StorageAccount)'
    ContainerName: '$(StorageContainer)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: infrastructure
    ArtifactName: infrastructure
    publishLocation: Container
